repos:
- hooks:
  - id: trailing-whitespace
    exclude: (docs|\.phan|.vscode|composer.lock)
  - id: end-of-file-fixer
    exclude: (docs|\.phan|.vscode|composer.lock)
    id: check-json
    exclude: (docs|\.phan|.vscode|composer.lock)
  - id: check-xml
    exclude: (docs|\.phan|.vscode|composer.lock)
  - id: check-yaml
    exclude: (docs|\.phan|.vscode|composer.lock)
  - id: check-added-large-files
    exclude: (docs|\.phan|.vscode|composer.lock)
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
- hooks:
  - id: commitizen
  repo: https://github.com/commitizen-tools/commitizen
  rev: v3.27.0
- hooks:
  - exclude: (tests\/__data-providers__)
    files: \.(php)$
    id: php-lint
  - args:
    - --standard=PSR1,PSR12,./phpcs.xml
    - -p
    exclude: (examples|test|\.phan)
    files: \.(php)$
    id: php-cs
  - id: php-unit
  - exclude: (examples|test)
    files: \.(php)$
    id: php-stan
  repo: https://github.com/digitalpulp/pre-commit-php.git
  rev: 1.4.0
- hooks:
  - exclude: (examples|test)
    id: phpmd
  repo: https://gitlab.com/daverona/pre-commit/php
  rev: 0.6.0
