name: Prod Upgrade Release

on:
  schedule:
    - cron: '6 2 * * 4'

jobs:
  prod_upgrade_release:
    env:
      DEP_UPGRADE_AUTHOR: dependabot
      DEP_UPGRADE_TYPE: direct:production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git fetch --tags
      - name: Set latest tag
        run: |
          {
            echo 'latest_tag<<EOF'
            git describe --tags --abbrev=0
            EOF
          }  >> "$GITHUB_ENV"
      - name: Set new tag
        run: |
          {
            echo 'new_tag<<EOF'
            echo "$latest_tag" | awk 'BEGIN { FS = "." } { print $1"."$2"."$3+1 }'
            EOF
          } >> "$GITHUB_ENV"
      - name: Set "has_new_prod_upgrade"
        run: |
          {
            echo 'has_new_prod_upgrade<<EOF'
            git log HEAD "$latest_tag" --author "$DEP_UPGRADE_AUTHOR" --grep "$DEP_UPGRADE_TYPE"
            EOF
          } >> "$GITHUB_ENV"
      - name: Create release when prod deps upgraded
        run: |
          if [ -n "$has_new_prod_upgrade" ]; then
              git tag -a "$new_tag" -m "$new_tag"
              git push --tags
              gh release create "$new_tag" --generate-notes --title "Dependency upgrade release"
          fi
