name: Prod Upgrade Release

on: push

permissions:
  contents: write

jobs:
  prod_upgrade_release:
    env:
      DEP_UPGRADE_AUTHOR: dependabot
      DEP_UPGRADE_TYPE: direct:production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git config --global user.email "no-reply@phpolar.org"
      - run: git config --global user.name "phpolar"
      - run: git fetch --all --unshallow
      - name: Set latest tag
        run: echo "latest_tag=$(git describe --tags --abbrev=0)" >> "$GITHUB_ENV"
      - name: Set new tag
        id: set-new-tag
        run: echo "NEW_TAG=$(echo $latest_tag | awk 'BEGIN { FS = "." } { print $1"."$2"."$3+1 }')" >> "$GITHUB_ENV"
      - name: Set "has_new_prod_upgrade"
        id: has-new-prod-upgrade
        run: |
          {
            echo 'has_new_prod_upgrade<<EOF'
            git log HEAD "$latest_tag" --author "$DEP_UPGRADE_AUTHOR" --grep "$DEP_UPGRADE_TYPE"
            echo EOF
          } >> "$GITHUB_OUTPUT"
      - name: Create release when prod deps upgraded
        if: ${{ steps.has-new-prod-upgrade.outputs.has_new_prod_upgrade != '' }}
        run: |
          git tag -a "$NEW_TAG" -m "$NEW_TAG"
          git push --tags
          gh release create "$NEW_TAG" --generate-notes --title "Dependency upgrade release"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
