name: Prod Upgrade Release
on:
  schedule:
    # every Sunday at 10:45AM UTC
    - cron: '45 10 * * 0'
permissions:
  contents: write
jobs:
  prod_upgrade_release:
    uses: phpolar/github-workflows/.github/workflows/prod-upgrade-release.yml@v1
    secrets: inherit
