name: Source code changes
on:
  pull_request:
    branches:
      - 'main'
    paths:
      - '**.php'
      - '!tests/**'
      - '!examples/**'
      - '!config/**'
      - '!.phan/**'
jobs:
  PHPMD:
    uses: phpolar/github-workflows/.github/workflows/phpmd.yml@v1
    secrets: inherit
